---
kind: pipeline
type: docker
name: validate

steps:
  - name: yamllint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -c ./cicd/.yamllint.yaml .

---
kind: template
load: build.yaml
data:
  registry_host: harbor.k8s.lan/k8s
  containerfile: ./deploy/container/Containerfile
  storage_driver: overlay
  format: oci
  context: .
  tlsverify: false

---
kind: secret
name: harbor_registry_drone_password
get:
  path: harbor-registry-drone-password
  name: harbor-robot-password

---
kind: secret
name: github_ssh_key
get:
  path: github-ssh-keys
  name: id_rsa
