---
kind: pipeline
type: docker
name: validate

steps:
  - name: yamllint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -c ./cicd/.yamllint.yaml .

---
kind: pipeline
type: docker
name: build

depends_on:
  - validate

steps:
  - name: test
    image: harbor-registry.devops.svc.cluster.local:5000/library/home-assistant:32
    commands:
      - ls -l

  # - name: init-01 build and push image
  #   image: quay.io/buildah/stable
  #   privileged: true
  #   environment:
  #     REGISTRY_HOST: "harbor.k8s.lan/library"
  #     CONTAINERFILE: "./deploy/container/Containerfile"
  #     STORAGE_DRIVER: "overlay"
  #     FORMAT: "oci"
  #     CONTEXT: "."
  #     TLSVERIFY: "false"
  #     USERNAME: "robot$library+drone"
  #     PASSWORD:
  #       from_secret: harbor_registry_password
  #   commands:
  #     - |
  #       echo "Build image..."
  #       buildah --storage-driver=$${STORAGE_DRIVER} bud --format=$${FORMAT} \
  #       --tls-verify=$${TLSVERIFY} --no-cache \
  #       -f $${CONTAINERFILE} \
  #       -t $${REGISTRY_HOST}/$${DRONE_REPO_NAME}:latest \
  #       -t $${REGISTRY_HOST}/$${DRONE_REPO_NAME}:$${DRONE_BUILD_NUMBER} \
  #       --layers=true $${CONTEXT}
  #     - |
  #       echo "Push image with latest tag..."
  #       buildah push --creds=$${USERNAME}:$${PASSWORD} \
  #       --tls-verify=$${TLSVERIFY} \
  #       $${REGISTRY_HOST}/$${DRONE_REPO_NAME}:latest \
  #       docker://$${REGISTRY_HOST}/$${DRONE_REPO_NAME}:latest
  #     - |
  #       echo "Push image with buildnumber tag..."
  #       buildah push --creds=$${USERNAME}:$${PASSWORD} \
  #       --tls-verify=$${TLSVERIFY} \
  #       --digestfile=/tmp/image-digest \
  #       $${REGISTRY_HOST}/$${DRONE_REPO_NAME}:$${DRONE_BUILD_NUMBER} \
  #       docker://$${REGISTRY_HOST}/$${DRONE_REPO_NAME}:$${DRONE_BUILD_NUMBER}

---
kind: secret
name: harbor_registry_password
get:
  path: harbor-registry-drone-password
  name: DRONE_PASSWORD

---
kind: secret
name: github_ssh_key
get:
  path: github-ssh-keys
  name: id_rsa
