---
kind: pipeline
type: docker
name: validate

steps:
  - name: prettier
    image: tmknom/prettier:latest
    commands:
      - prettier --config "./cicd/.prettierrc.yaml" --ignore-path "./cicd/.prettierignore.yaml" --check "./src/config/**/*.yaml"

  - name: yamllint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -c ./cicd/.yamllint.yaml .
