FROM docker.io/debian:bullseye-20221004-slim

RUN apt-get update && apt-get install -y \
    curl \
    jq

COPY ./src/shelly-init.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/shelly-init.sh

ENTRYPOINT ["/bin/bash"]